In [ ]:
# NumPy Array Operations Practice
# ===============================
#
#Create a 1D NumPy array with elements [2,4,6,8,10,12] and print it.
#Append the value 14 to the array and print the updated array.
#Create a 2D NumPy array [[2,4],[6,8]].
#Insert the value 111 at column index 1 (axis=1) in the 2D array.
#Print the array after insertion.
#Delete the element at index 0 from the array.
#Print the final array.
import numpy as np
a=np.array([2,4,6,8,10,12])
print(a)
a=np.append(a,14)
print(a)
a=np.array([[2,4],[6,8]])
a=np.insert(a,1,111,axis=1)
print(a)
a=np.delete(a,[0])
print(a)

[ 2  4  6  8 10 12]
[ 2  4  6  8 10 12 14]
[[  2 111   4]
 [  6 111   8]]
[111   4   6 111   8]
