In [2]:
import numpy as np
a=[1,2,3,4]
b=[5,6,7,8]
print(a+b)


[1, 2, 3, 4, 5, 6, 7, 8]


In [9]:
a1=np.array([2,4,6,8])
a2=np.array([10,12,14,16])
print(np.concatenate([a1,a2]))

[ 2  4  6  8 10 12 14 16]


In [22]:
arr1=np.array([[4,8],[12,16],[20,24]])
arr2=np.array([[5,10],[15,20],[25,30]])
print(np.concatenate([arr1,arr2],axis=0))
print(np.hstack([arr1,arr2]))
print(np.vstack([arr1,arr2]))
      

[[ 4  8]
 [12 16]
 [20 24]
 [ 5 10]
 [15 20]
 [25 30]]
[[ 4  8  5 10]
 [12 16 15 20]
 [20 24 25 30]]
[[ 4  8]
 [12 16]
 [20 24]
 [ 5 10]
 [15 20]
 [25 30]]


In [31]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.array_split(a,2))

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]
