In [3]:
import numpy as np
a=np.array([5,4,3,2,6,7,9,8])
a=np.sort(a)
print(a)

[2 3 4 5 6 7 8 9]


In [6]:
b=np.where(a==4)
print(b)
c=np.where(a%2==0)
print(c)

(array([2]),)
(array([0, 2, 4, 6]),)


In [9]:
ss=np.array([1,2,3,4,5,6,7])
z=np.searchsorted(ss,3)
print(z)

2


In [12]:
a=np.array([1,2,3,4,5,6])
b=[True,False,True,False,True,False]
c=a[b]
odd=a%2==1
d=a[odd]
print(d)
print(c)

[1 3 5]
[1 3 5]
